#include "fixture_api.hpp"

#include <angelscript.h>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <vector>

namespace {
    struct Stream : asIBinaryStream {
        std::vector<unsigned char> bytes;
        int Read(void*, asUINT) override { return -1; }
        int Write(const void* data, asUINT size) override {
            const auto* begin = static_cast<const unsigned char*>(data);
            bytes.insert(bytes.end(), begin, begin + size);
            return 0;
        }
    };

    void check(int result) {
        if (result < 0) throw std::runtime_error("AngelScript fixture generation failed");
    }

    void message(const asSMessageInfo* info, void*) {
        std::cerr << info->section << ':' << info->row << ": " << info->message << '\n';
    }

    void save(std::ostream& output, asIScriptModule& module, const char* name, bool stripped) {
        Stream stream;
        check(module.SaveByteCode(&stream, stripped));
        output << "inline constexpr unsigned char " << name << "[] = {\n";
        for (std::size_t i = 0; i < stream.bytes.size(); ++i) {
            output << static_cast<unsigned>(stream.bytes[i]) << ',';
            if (i % 20 == 19) output << '\n';
        }
        output << "\n};\n";
    }
}

int main(int argc, char** argv) {
    if (argc != 2) return 1;
    auto* engine = asCreateScriptEngine();
    if (!engine) return 1;
    try {
        check(engine->SetMessageCallback(asFUNCTION(message), nullptr, asCALL_CDECL));
        // Registration order deliberately differs from bytecode use order.
        check(engine->RegisterGlobalFunction("void record(int)", asFUNCTION(fixture::record), asCALL_CDECL));
        check(engine->RegisterGlobalFunction("float combine(int, float, int)", asFUNCTION(fixture::combine), asCALL_CDECL));
        check(engine->RegisterGlobalFunction("float subtract(float, float)", asFUNCTION(fixture::subtract), asCALL_CDECL));
        check(engine->RegisterGlobalFunction("float sqrt(float)", asFUNCTION(fixture::root), asCALL_CDECL));
        check(engine->RegisterGlobalFunction("float noargs()", asFUNCTION(fixture::noargs), asCALL_CDECL));
        check(engine->RegisterGlobalFunction("uint echo(uint)", asFUNCTION(fixture::echo), asCALL_CDECL));
        check(engine->RegisterGlobalFunction("void scalars(bool, int8, uint16)", asFUNCTION(fixture::scalars), asCALL_CDECL));
        check(engine->SetDefaultNamespace("other"));
        check(engine->RegisterGlobalFunction("float subtract(float, float)", asFUNCTION(fixture::add), asCALL_CDECL));
        check(engine->SetDefaultNamespace(""));

        const char* source = R"(
            float hypotenuse(float a, float b) { return sqrt(a*a + b*b); }
            float direct(float a) { return sqrt(a); }
            float difference(float a, float b) { return subtract(a, b); }
            float mixed(int a, float b, int c) { return combine(a, b, c); }
            float chained(float a, float b) { return subtract(sqrt(a), sqrt(b)); }
            void notify(int a) { record(a); }
            float noarguments() { return noargs(); }
            float qualified(float a, float b) { return other::subtract(a, b); }
            uint unsignedEcho(uint a) { return echo(a); }
            void scalarargs(bool a, int8 b, uint16 c) { scalars(a, b, c); }
        )";
        auto* module = engine->GetModule("callsys", asGM_ALWAYS_CREATE);
        check(module->AddScriptSection("callsys.as", source));
        check(module->Build());

        // Confirm representative expectations in AngelScript's own VM too.
        auto* context = engine->CreateContext();
        check(context->Prepare(module->GetFunctionByName("mixed")));
        check(context->SetArgDWord(0, static_cast<asDWORD>(-4)));
        check(context->SetArgFloat(1, 2.5f));
        check(context->SetArgDWord(2, 3));
        if (context->Execute() != asEXECUTION_FINISHED || context->GetReturnFloat() != 3.5f)
            throw std::runtime_error("Unexpected AngelScript mixed-argument result");
        check(context->Prepare(module->GetFunctionByName("chained")));
        check(context->SetArgFloat(0, 81.0f));
        check(context->SetArgFloat(1, 16.0f));
        if (context->Execute() != asEXECUTION_FINISHED || context->GetReturnFloat() != 5.0f)
            throw std::runtime_error("Unexpected AngelScript chained-call result");
        check(context->Prepare(module->GetFunctionByName("scalarargs")));
        check(context->SetArgByte(0, 1));
        check(context->SetArgByte(1, static_cast<asBYTE>(-7)));
        check(context->SetArgWord(2, 513));
        if (context->Execute() != asEXECUTION_FINISHED || fixture::recorded != 506)
            throw std::runtime_error("Unexpected AngelScript small-scalar result");
        context->Release();

        std::ofstream output(argv[1]);
        output << "// Generated by AngelScript 2.38.0; do not edit.\n#pragma once\n";
        save(output, *module, "fixture_asbc", false);
        save(output, *module, "fixture_stripped_asbc", true);
        auto* plain = engine->GetModule("plain", asGM_ALWAYS_CREATE);
        check(plain->AddScriptSection("plain.as", "int square(int x) { return x*x; }"));
        check(plain->Build());
        save(output, *plain, "plain_asbc", true);
        output.close();
        if (!output) throw std::runtime_error("Could not write fixture header");
        engine->ShutDownAndRelease();
        return 0;
    } catch (const std::exception& error) {
        std::cerr << error.what() << '\n';
        engine->ShutDownAndRelease();
        return 1;
    }
}
